kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: morphling-ui
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
      - pods
      - nodes
    verbs:
      - list
  - apiGroups:
      - tuning.kubedl.io
    resources:
      - profilingexperiments
      - trials
      - samplings
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: morphling-ui
  namespace: morphling-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: morphling-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: morphling-ui
subjects:
  - kind: ServiceAccount
    name: morphling-ui
    namespace: morphling-system
