apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphling-mysql
  namespace: morphling-system
  labels:
    app: morphling
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphling
      component: mysql
  template:
    metadata:
      name: morphling-mysql
      labels:
        app: morphling
        component: mysql
    spec:
      containers:
        - name: morphling-mysql
          image: kubedl/mysql
          args:
            - --datadir
            - /var/lib/mysql/datadir
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "morphling"
            #            valueFrom:
            #              secretKeyRef:
            #                name: morphling-mysql-secrets
            #                key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: "morphling"
          ports:
            - name: dbapi
              containerPort: 3306
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysql -D ${MYSQL_DATABASE} -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: morphling-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: morphling-mysql
          persistentVolumeClaim:
            claimName: morphling-mysql
