apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid
  namespace: morphling-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: grid
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        deployment: grid
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/delphin/algorithm-chocolate:5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:6789
                - -service=manager.v1alpha3.Suggestion
            failureThreshold: 12
            initialDelaySeconds: 10
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 1
          name: sampling
          ports:
            - containerPort: 6789
              name: morphling-api
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:6789
                - -service=manager.v1alpha3.Suggestion
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 5Gi
              memory: 100Mi
            requests:
              cpu: 50m
              ephemeral-storage: 500Mi
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
